fragment PropertyValue on GenericValue {
    ... on Value {
        valuePayload: payload
        valueRawPayload: raw_payload
    }
    ... on LinkValue {
        linkPayload: payload {
            ...RecordIdentity
        }
    }
    ... on TreeValue {
        treePayload: payload {
            record {
                ...RecordIdentity
            }
        }
    }
}

query ExplorerV2LibraryData(
    $libraryId: ID!
    $attributeIds: [ID!]!
    $pagination: RecordsPagination
    $filters: [RecordFilterInput]
    $multipleSort: [RecordSortInput!]
    $searchQuery: String
) {
    records(
        library: $libraryId
        filters: $filters
        pagination: $pagination
        multipleSort: $multipleSort
        searchQuery: $searchQuery
    ) {
        totalCount
        list {
            ...RecordIdentity
            active
            permissions {
                create_record
                delete_record
            }
            properties(attributeIds: $attributeIds) {
                attributeId
                values {
                    ...PropertyValue
                }
            }
        }
    }
}

fragment ExplorerV2LinkProperty on GenericValue {
    id_value
    ... on LinkValue {
        payload {
            ...RecordIdentity
            properties(attributeIds: $attributeIds) {
                attributeId
                values {
                    ...PropertyValue
                }
            }
        }
    }
}

query ExplorerV2LinkData($attributeIds: [ID!]!, $parentLibraryId: ID!, $parentRecordId: String, $linkAttributeId: ID!) {
    records(
        library: $parentLibraryId
        filters: [{field: "id", condition: EQUAL, value: $parentRecordId}]
        retrieveInactive: true
    ) {
        list {
            id
            whoAmI {
                id
                library {
                    id
                }
            }
            property(attribute: $linkAttributeId) {
                ...ExplorerV2LinkProperty
            }
        }
    }
}
