mutation SaveAttribute($attribute: AttributeInput) {
    saveAttribute(attribute: $attribute) {
        id
    }
}

mutation DeleteAttribute($id: ID!) {
    deleteAttribute(id: $id) {
        id
    }
}

query getLinkAttributeSmartFilter($filters: AttributesFiltersInput) {
    attributes(filters: $filters) {
        list {
            ... on LinkAttribute {
                smart_filter {
                    enable
                    through {
                        id
                    }
                }
            }
        }
    }
}
