default:
  image: node:20-alpine3.21
  interruptible: true
  tags:
    - docker-dev

workflow:
  auto_cancel:
    on_new_commit: interruptible
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_TAG
      auto_cancel:
        on_new_commit: none
    - if: $CI_MERGE_REQUEST_TITLE =~ /^Draft:/ || $CI_MERGE_REQUEST_TITLE =~ /^WIP:/
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      auto_cancel:
        on_job_failure: all
    - when: always

.no_tag_rule: &no_tag_rule
  if: $CI_COMMIT_TAG
  when: never

.no_duplicate_rule: &no_duplicate_rule
  if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
  when: never

.mr_rule: &mr_rule
  if: $CI_PIPELINE_SOURCE == "merge_request_event"
  when: on_success

.new_lib_installed_changes: &new_lib_installed_changes yarn.lock

variables:
  GIT_DEPTH: 1 # clone only the last commit to speed up the pipeline
  NODE_ENV: test
  YARN_CACHE_FOLDER: .yarn_cache
  # https://docs.gitlab.com/runner/configuration/feature-flags/
  FF_USE_FASTZIP: "true"
  FF_TIMESTAMPS: "true"
  # https://docs.gitlab.com/ci/runners/configure_runners/#artifact-and-cache-settings
  ARTIFACT_COMPRESSION_LEVEL: "default"
  # bigger archive, but should not be a problem for local storage, or local s3 storage
  CACHE_COMPRESSION_LEVEL: "fastest"
  # For ci development, could be removed once ci goes to production
  DISABLE_CHECK_JOBS: "false"
  DISABLE_TEST_JOBS: "false"
  DISABLE_E2E_JOBS: "false"
  DISABLE_BUILD_DOCKER_JOBS: "false"
  DISABLE_PUBLISH_NPM_JOBS: "false"
  # If use npmjs.org public registry
  NPM_TOKEN: ""

stages:
  - test
  - build

.yarn_cache: &yarn_cache
  key:
    files:
      - yarn.lock
  paths:
    - .yarn_cache
  policy: pull

##########
## Other checks
## For merge requests and merge in develop/main branches
.check_ci_rules: &check_ci_rules
  - if: $DISABLE_CHECK_JOBS == "true"
    when: never
  - *no_tag_rule
  - *no_duplicate_rule
  - *mr_rule

lint:
  stage: test
  script:
    - yarn workspaces focus --all
    - yarn run lint --format gitlab
  cache:
    <<: *yarn_cache
    policy: pull-push
  rules: *check_ci_rules
  artifacts:
    reports:
      codequality: gl-codequality.json

license-check:
  stage: test
  script:
    - yarn workspaces focus leav-monorepo
    - yarn run license:check
  cache:
    <<: *yarn_cache
  rules: *check_ci_rules

tscheck:
  stage: test
  script:
    - yarn workspaces focus --all
    - yarn run tscheck
  cache:
    <<: *yarn_cache
  rules: *check_ci_rules

translations-check:
  stage: test
  script:
    - node ./scripts/compareTranslations.js
  rules: *check_ci_rules

## Other checks
##########

##########
## Unit tests
## For merge requests and merge in develop/main branches
.disable_test_rule: &disable_test_rule
  if: $DISABLE_TEST_JOBS == "true"
  when: never

libs/app-root-path-unit-tests:
  stage: test
  script:
    - yarn workspaces focus @leav/app-root-path
    - yarn workspace @leav/app-root-path run test:ci
  cache:
    <<: *yarn_cache
  rules:
    - *disable_test_rule
    - *no_tag_rule
    - *no_duplicate_rule
    - <<: *mr_rule
      changes:
        - *new_lib_installed_changes
        - libs/app-root-path/**/*

libs/config-manager-unit-tests:
  stage: test
  script:
    - yarn workspaces focus @leav/config-manager
    - yarn workspace @leav/config-manager run test:ci
  cache:
    <<: *yarn_cache
  rules:
    - *disable_test_rule
    - *no_tag_rule
    - *no_duplicate_rule
    - <<: *mr_rule
      changes:
        - *new_lib_installed_changes
        - libs/config-manager/**/*

libs/message-broker-unit-tests:
  stage: test
  script:
    - yarn workspaces focus @leav/message-broker
    - yarn workspace @leav/message-broker run test:ci
  cache:
    <<: *yarn_cache
  rules:
    - *disable_test_rule
    - *no_tag_rule
    - *no_duplicate_rule
    - <<: *mr_rule
      changes:
        - *new_lib_installed_changes
        - libs/message-broker/**/*

libs/monitoring-server-unit-tests:
  stage: test
  script:
    - yarn workspaces focus @leav/monitoring-server
    - yarn workspace @leav/monitoring-server run test:ci
  cache:
    <<: *yarn_cache
  rules:
    - *disable_test_rule
    - *no_tag_rule
    - *no_duplicate_rule
    - <<: *mr_rule
      changes:
        - *new_lib_installed_changes
        - libs/logger/**/*
        - libs/monitoring-server/**/*

# Split libs/ui-unit-tests job to run in parallel for faster execution
libs/ui-unit-tests/explorer:
  stage: test
  script:
    - yarn workspaces focus @leav/ui
    - yarn workspace @leav/ui run test:ci --testPathPattern="src/components/Explorer"
  cache:
    <<: *yarn_cache
  rules:
    - *disable_test_rule
    - *no_tag_rule
    - *no_duplicate_rule
    - <<: *mr_rule
      changes:
        - *new_lib_installed_changes
        - libs/ui/**/*

libs/ui-unit-tests/record-edition/library-items-list:
  stage: test
  script:
    - yarn workspaces focus @leav/ui
    - yarn workspace @leav/ui run test:ci --testPathPattern="src/components/RecordEdition|src/components/LibraryItemsList"
  cache:
    <<: *yarn_cache
  rules:
    - *disable_test_rule
    - *no_tag_rule
    - *no_duplicate_rule
    - <<: *mr_rule
      changes:
        - *new_lib_installed_changes
        - libs/ui/**/*

libs/ui-unit-tests/rest:
  stage: test
  script:
    - yarn workspaces focus @leav/ui
    - yarn workspace @leav/ui run test:ci --testPathIgnorePatterns="src/components/RecordEdition|src/components/LibraryItemsList|src/components/Explorer"
  cache:
    <<: *yarn_cache
  rules:
    - *disable_test_rule
    - *no_tag_rule
    - *no_duplicate_rule
    - <<: *mr_rule
      changes:
        - *new_lib_installed_changes
        - libs/ui/**/*

libs/utils-unit-tests:
  stage: test
  script:
    - yarn workspaces focus @leav/utils
    - yarn workspace @leav/utils run test:ci
  cache:
    <<: *yarn_cache
  rules:
    - *disable_test_rule
    - *no_tag_rule
    - *no_duplicate_rule
    - <<: *mr_rule
      changes:
        - *new_lib_installed_changes
        - libs/utils/**/*

apps/admin-unit-tests:
  stage: test
  script:
    - yarn workspaces focus admin
    - yarn workspace admin run test:ci
  cache:
    <<: *yarn_cache
  rules:
    - *disable_test_rule
    - *no_tag_rule
    - *no_duplicate_rule
    - <<: *mr_rule
      changes:
        - *new_lib_installed_changes
        - apps/admin/**/*

apps/app-studio-unit-tests:
  stage: test
  script:
    - yarn workspaces focus app-studio
    - yarn workspace app-studio run test:ci
  cache:
    <<: *yarn_cache
  rules:
    - *disable_test_rule
    - *no_tag_rule
    - *no_duplicate_rule
    - <<: *mr_rule
      changes:
        - *new_lib_installed_changes
        - apps/app-studio/**/*
        - libs/ui/**/*
        - libs/utils/**/*

apps/automate-scan-unit-tests:
  stage: test
  script:
    - yarn workspaces focus automate-scan
    - yarn workspace automate-scan run test:ci
  cache:
    <<: *yarn_cache
  rules:
    - *disable_test_rule
    - *no_tag_rule
    - *no_duplicate_rule
    - <<: *mr_rule
      changes:
        - *new_lib_installed_changes
        - apps/automate-scan/**/*
        - libs/app-root-path/**/*
        - libs/config-manager/**/*
        - libs/logger/**/*
        - libs/monitoring-server/**/*
        - libs/utils/**/*

apps/core-unit-tests:
  stage: test
  script:
    - yarn workspaces focus core
    - yarn workspace core run test:ci
  cache:
    <<: *yarn_cache
  rules:
    - *disable_test_rule
    - *no_tag_rule
    - *no_duplicate_rule
    - <<: *mr_rule
      changes:
        - *new_lib_installed_changes
        - apps/core/**/*
        - libs/app-root-path/**/*
        - libs/config-manager/**/*
        - libs/logger/**/*
        - libs/message-broker/**/*
        - libs/monitoring-server/**/*
        - libs/utils/**/*

apps/data-studio-unit-tests:
  stage: test
  script:
    - yarn workspaces focus data-studio
    - yarn workspace data-studio run test:ci
  cache:
    <<: *yarn_cache
  rules:
    - *disable_test_rule
    - *no_tag_rule
    - *no_duplicate_rule
    - <<: *mr_rule
      changes:
        - *new_lib_installed_changes
        - apps/data-studio/**/*
        - libs/ui/**/*
        - libs/utils/**/*

apps/login-unit-tests:
  stage: test
  script:
    - yarn workspaces focus login
    - yarn workspace login run test:ci
  cache:
    <<: *yarn_cache
  rules:
    - *disable_test_rule
    - *no_tag_rule
    - *no_duplicate_rule
    - <<: *mr_rule
      changes:
        - *new_lib_installed_changes
        - apps/login/**/*
        - libs/ui/**/*

apps/logs-collector-unit-tests:
  stage: test
  script:
    - yarn workspaces focus logs-collector
    - yarn workspace logs-collector run test:ci
  cache:
    <<: *yarn_cache
  rules:
    - *disable_test_rule
    - *no_tag_rule
    - *no_duplicate_rule
    - <<: *mr_rule
      changes:
        - *new_lib_installed_changes
        - apps/logs-collector/**/*
        - libs/app-root-path/**/*
        - libs/config-manager/**/*
        - libs/logger/**/*
        - libs/message-broker/**/*
        - libs/monitoring-server/**/*
        - libs/utils/**/*

apps/portal-unit-tests:
  stage: test
  script:
    - yarn workspaces focus portal
    - yarn workspace portal run test:ci
  cache:
    <<: *yarn_cache
  rules:
    - *disable_test_rule
    - *no_tag_rule
    - *no_duplicate_rule
    - <<: *mr_rule
      changes:
        - *new_lib_installed_changes
        - apps/portal/**/*
        - libs/ui/**/*
        - libs/utils/**/*

apps/preview-generator-unit-tests:
  stage: test
  script:
    - yarn workspaces focus preview-generator
    - yarn workspace preview-generator run test:ci
  cache:
    <<: *yarn_cache
  rules:
    - *disable_test_rule
    - *no_tag_rule
    - *no_duplicate_rule
    - <<: *mr_rule
      changes:
        - *new_lib_installed_changes
        - apps/preview-generator/**/*
        - libs/app-root-path/**/*
        - libs/config-manager/**/*
        - libs/logger/**/*
        - libs/monitoring-server/**/*
        - libs/utils/**/*

apps/sync-scan-unit-tests:
  stage: test
  script:
    - yarn workspaces focus sync-scan
    - yarn workspace sync-scan run test:ci
  cache:
    <<: *yarn_cache
  rules:
    - *disable_test_rule
    - *no_tag_rule
    - *no_duplicate_rule
    - <<: *mr_rule
      changes:
        - *new_lib_installed_changes
        - apps/sync-scan/**/*
        - libs/app-root-path/**/*
        - libs/config-manager/**/*
        - libs/message-broker/**/*
        - libs/utils/**/*
## Unit tests
##########

##########
## E2E tests
## For merge requests and merge in develop/main branches
.disable_e2e_rule: &disable_e2e_rule
  if: $DISABLE_E2E_JOBS == "true"
  when: never

.e2e_service_arangodb: &e2e_service_arangodb
  name: arangodb:3.12
  alias: arangodb
  variables:
    ARANGO_NO_AUTH: "1"

.e2e_service_rabbitmq: &e2e_service_rabbitmq
  name: rabbitmq:3.13-management-alpine
  alias: rabbitmq

.e2e_service_redis: &e2e_service_redis
  name: redis:latest
  alias: redis

integration-test-core:
  stage: test
  services:
    - *e2e_service_arangodb
  variables:
    ARANGO_URL: "http://root:@arangodb:8529"
    APP_ROOT_PATH: "$CI_PROJECT_DIR/apps/core"
  script:
    - yarn workspaces focus core
    - yarn workspace core run test:integration
  cache:
    <<: *yarn_cache
  rules:
    - *disable_e2e_rule
    - *no_tag_rule
    - *no_duplicate_rule
    - <<: *mr_rule
      changes:
        - *new_lib_installed_changes
        - apps/core/**/*
        - libs/app-root-path/**/*
        - libs/config-manager/**/*
        - libs/logger/**/*
        - libs/message-broker/**/*
        - libs/monitoring-server/**/*
        - libs/utils/**/*

integration-test-automate-scan:
  stage: test
  services:
    - *e2e_service_rabbitmq
    - *e2e_service_redis
  variables:
    APP_ROOT_PATH: "$CI_PROJECT_DIR/apps/automate-scan"
    AMQP_HOST: "rabbitmq"
    AMQP_PORT: "5672"
    AMQP_USERNAME: "guest"
    AMQP_PWD: "guest"
    REDIS_HOST: "redis"
    REDIS_PORT: "6379"
  script:
    - yarn workspaces focus automate-scan
    - yarn workspace automate-scan run test:integration
  cache:
    <<: *yarn_cache
  rules:
    - *disable_e2e_rule
    - *no_tag_rule
    - *no_duplicate_rule
    - <<: *mr_rule
      changes:
        - *new_lib_installed_changes
        - apps/automate-scan/**/*
        - libs/app-root-path/**/*
        - libs/config-manager/**/*
        - libs/logger/**/*
        - libs/message-broker/**/*
        - libs/monitoring-server/**/*
        - libs/utils/**/*

e2e-api:
  stage: test
  services:
    - *e2e_service_arangodb
    - *e2e_service_rabbitmq
    - *e2e_service_redis
    # Dont need elasticsearch for api tests, but could be added if needed (see file history)
  variables:
    ARANGO_URL: "http://root:@arangodb:8529"
    AUTH_KEY: "123456789"
    AMQP_HOST: "rabbitmq"
    AMQP_PORT: "5672"
    AMQP_USERNAME: "guest"
    AMQP_PWD: "guest"
    APP_ROOT_PATH: "$CI_PROJECT_DIR/apps/core"
    IMPORT_DIR: "$CI_PROJECT_DIR/imports"
    DISK_CACHE_DIRECTORY: "$CI_PROJECT_DIR/cache"
    FILES_ROOT_PATHS: "files1:$CI_PROJECT_DIR/files"
    REDIS_HOST: "redis"
    REDIS_PORT: "6379"
  script:
    - yarn workspaces focus core
    - yarn workspace core run test:e2e:api
  cache:
    <<: *yarn_cache
  rules:
    - *disable_e2e_rule
    - *no_tag_rule
    - *no_duplicate_rule
    - <<: *mr_rule
      changes:
        - *new_lib_installed_changes
        - apps/core/**/*
        - libs/app-root-path/**/*
        - libs/config-manager/**/*
        - libs/logger/**/*
        - libs/message-broker/**/*
        - libs/monitoring-server/**/*
        - libs/utils/**/*

e2e-indexation-manager:
  stage: test
  services:
    - *e2e_service_arangodb
    - *e2e_service_rabbitmq
    - *e2e_service_redis
    # Dont need elasticsearch for api tests, but could be added if needed (see file history)
  variables:
    ARANGO_URL: "http://root:@arangodb:8529"
    AUTH_KEY: "123456789"
    AMQP_HOST: "rabbitmq"
    AMQP_PORT: "5672"
    AMQP_USERNAME: "guest"
    AMQP_PWD: "guest"
    APP_ROOT_PATH: "$CI_PROJECT_DIR/apps/core"
    REDIS_HOST: "redis"
    REDIS_PORT: "6379"
  script:
    - yarn workspaces focus core
    - yarn workspace core run test:e2e:indexationManager
  cache:
    <<: *yarn_cache
  rules:
    - *disable_e2e_rule
    - *no_tag_rule
    - *no_duplicate_rule
    - <<: *mr_rule
      changes:
        - *new_lib_installed_changes
        - apps/core/**/*
        - libs/app-root-path/**/*
        - libs/config-manager/**/*
        - libs/logger/**/*
        - libs/message-broker/**/*
        - libs/monitoring-server/**/*
        - libs/utils/**/*

e2e-sync-scan:
  stage: test
  services:
    - *e2e_service_rabbitmq
  variables:
    AMQP_HOST: "rabbitmq"
    AMQP_PORT: "5672"
    AMQP_USERNAME: "guest"
    AMQP_PWD: "guest"
    APP_ROOT_PATH: "$CI_PROJECT_DIR/apps/sync-scan"
    ALLOW_FILES_LIST: ""
    IGNORE_FILES_LIST: ""
  script:
    - yarn workspaces focus sync-scan
    - yarn workspace sync-scan run test:e2e
  cache:
    <<: *yarn_cache
  rules:
    - *disable_e2e_rule
    - *no_tag_rule
    - *no_duplicate_rule
    - <<: *mr_rule
      changes:
        - *new_lib_installed_changes
        - apps/sync-scan/**/*
        - libs/app-root-path/**/*
        - libs/config-manager/**/*
        - libs/logger/**/*
        - libs/message-broker/**/*
        - libs/utils/**/*

## E2E tests
##########

##########
## Build / push docker images
## For develop branch and release/tags
.docker_in_docker_image: &docker_in_docker_image docker:28.2.2-dind
.docker_image: &docker_image docker:28.2.2-cli

.docker_build_variables: &docker_build_variables
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_BUILDKIT: 1

.default_docker_build: &default_docker_build
  image: *docker_image
  services:
    - *docker_in_docker_image
  stage: build
  rules:
    - if: $DISABLE_BUILD_DOCKER_JOBS == "true"
      when: never
    - if: ($CI_COMMIT_TAG || $CI_COMMIT_BRANCH == "develop") && $DOCKER_PLATFORM == "linux/arm64"
      needs:
        - job: build-docker-arm64
      when: on_success
    - if: ($CI_COMMIT_TAG || $CI_COMMIT_BRANCH == "develop") && $DOCKER_PLATFORM == "linux/amd64"
      when: on_success
  variables:
    <<: *docker_build_variables
  parallel:
    matrix:
      - DOCKER_PLATFORM:
          - linux/amd64
          - linux/arm64
  before_script:
    - apk add --no-cache jq findutils
    # Check if CI_REGISTRY_USER is set to skip docker login for gitlab-ci-local
    - |
      echo "Login to docker registry if CI_REGISTRY_USER is defined"
      if [ -n "$CI_REGISTRY_USER" ]; then
        echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
        export DOCKER_PUSH="--push"
      else
        echo "CI_REGISTRY_USER non défini, skip docker login"
        export DOCKER_PUSH=""
      fi
    # Use different image tag for arm64 to avoid push conflict.
    # By default, latest push would have override first push (amd64 generally)
    # A solution would be to build image with single `docker buildx build` command and use --platform linux/amd64,linux/arm64 option,
    # Another solution could be to use `docker buildx imagetools create` from two image tag/sha
    # But because arm64 image are not allways built, this could result to a desynchronized code for same tag !
    - |
      echo "Defined docker image tag depending on CI_COMMIT_TAG and DOCKER_PLATFORM"
      if [ "$DOCKER_PLATFORM" == "linux/arm64" ]; then
        DOCKER_IMAGE_TAG_SUFFIX="-arm64"
      else
        DOCKER_IMAGE_TAG_SUFFIX=""
      fi
      if [ -n "$CI_COMMIT_TAG" ]; then
        export DOCKER_IMAGE_TAG="--tag $CI_REGISTRY_IMAGE/$DOCKER_IMAGE_APP:$CI_COMMIT_TAG$DOCKER_IMAGE_TAG_SUFFIX"
        export DOCKER_IMAGE_LATEST="--tag $CI_REGISTRY_IMAGE/$DOCKER_IMAGE_APP:latest$DOCKER_IMAGE_TAG_SUFFIX"
      else
        export DOCKER_IMAGE_TAG="--tag $CI_REGISTRY_IMAGE/$DOCKER_IMAGE_APP:develop$DOCKER_IMAGE_TAG_SUFFIX"
        export DOCKER_IMAGE_LATEST=""
      fi
    # Necessary to build linux/arm64 images on amd64 runners, use qemu !
    # This will create application/vnd.oci.image.index.v1+json mediaType instead of application/vnd.docker.distribution.manifest.v2+json mediaType
    # Not a problem, but gitlab registry will display a warning and wont be able to compute image size
    - |
      echo "Create docker buildx builder if DOCKER_PLATFORM is linux/arm64"
      if [ "$DOCKER_PLATFORM" == "linux/arm64" ]; then
        docker buildx create --use --driver docker-container --name builder
      fi
  after_script:
    - |
      echo "Remove docker buildx builder if DOCKER_PLATFORM is linux/arm64" 
      if [ "$DOCKER_PLATFORM" == "linux/arm64" ]; then
        docker buildx rm builder
      fi

# Write version to package.json and manifest.json
.set_version: &set_version
  - |
    if [ -z "$CI_COMMIT_TAG" ]; then
      echo "Setting version to develop ($CI_COMMIT_SHA)"
      find \( -name "package.json" -o -name "manifest.json" \) \
        -not -path "*/node_modules/*" -not -path "*/__tests__/*" -type f \
        -exec sh -c 'jq ".version = \"develop ($CI_COMMIT_SHA)\"" {} > tmpfile && mv tmpfile {}' \;
    fi

# May be replace with a child pipeline for docker image build
# Or use https://docs.docker.com/build/building/multi-platform/ if performance are good enough,
# but probably not will we use qemu !
build-docker-arm64:
  stage: build
  when: manual
  allow_failure: true
  script:
    - echo "Build arm64 docker images on demand only"
  rules:
    - if: $DISABLE_BUILD_DOCKER_JOBS == "true"
      when: never
    - if: $CI_COMMIT_TAG || $CI_COMMIT_BRANCH == "develop"
      when: manual

build-docker-core:
  <<: *default_docker_build
  variables:
    <<: *docker_build_variables
    DOCKER_IMAGE_APP: "core"
  script:
    - *set_version
    - docker buildx build
      --platform $DOCKER_PLATFORM
      --file docker/DOCKERFILES/build/core.Dockerfile
      --label "LEAV Engine"
      --label "Core"
      $DOCKER_IMAGE_TAG
      $DOCKER_IMAGE_LATEST
      $DOCKER_PUSH
      .

build-docker-preview-generator:
  <<: *default_docker_build
  variables:
    <<: *docker_build_variables
    DOCKER_IMAGE_APP: "preview-generator"
  script:
    - *set_version
    - docker buildx build
      --platform $DOCKER_PLATFORM
      --file docker/DOCKERFILES/build/generic.Dockerfile
      --build-arg APP=$DOCKER_IMAGE_APP
      --target runner-preview-generator
      --label "LEAV Engine"
      --label "Preview Generator"
      $DOCKER_IMAGE_TAG
      $DOCKER_IMAGE_LATEST
      $DOCKER_PUSH
      .

build-docker-automate-scan:
  <<: *default_docker_build
  variables:
    <<: *docker_build_variables
    DOCKER_IMAGE_APP: "automate-scan"
  script:
    - *set_version
    - docker buildx build
      --platform $DOCKER_PLATFORM
      --file docker/DOCKERFILES/build/generic.Dockerfile
      --build-arg APP=$DOCKER_IMAGE_APP
      --target runner
      --label "LEAV Engine"
      --label "Automate Scan"
      $DOCKER_IMAGE_TAG
      $DOCKER_IMAGE_LATEST
      $DOCKER_PUSH
      .

build-docker-sync-scan:
  <<: *default_docker_build
  variables:
    <<: *docker_build_variables
    DOCKER_IMAGE_APP: "sync-scan"
  script:
    - *set_version
    - docker buildx build
      --platform $DOCKER_PLATFORM
      --file docker/DOCKERFILES/build/generic.Dockerfile
      --build-arg APP=$DOCKER_IMAGE_APP
      --target runner
      --label "LEAV Engine"
      --label "Sync scan"
      $DOCKER_IMAGE_TAG
      $DOCKER_IMAGE_LATEST
      $DOCKER_PUSH
      .

build-docker-logs-collector:
  <<: *default_docker_build
  variables:
    <<: *docker_build_variables
    DOCKER_IMAGE_APP: "logs-collector"
  script:
    - *set_version
    - docker buildx build
      --platform $DOCKER_PLATFORM
      --file docker/DOCKERFILES/build/generic.Dockerfile
      --build-arg APP=$DOCKER_IMAGE_APP
      --target runner
      --label "LEAV Engine"
      --label "Logs Collector"
      $DOCKER_IMAGE_TAG
      $DOCKER_IMAGE_LATEST
      $DOCKER_PUSH
      .

## Build / push docker images
##########

##########
## Publish npm packages
.disable_publish_npm_rule: &disable_publish_npm_rule
  if: $DISABLE_PUBLISH_NPM_JOBS == "true"
  when: never

.login_npm_registry_script: &login_npm_registry_script
  - |
    if [ -n "$NPM_TOKEN" ]; then
      echo "Login to public npm registry with NPM_TOKEN"
      echo "npmAuthToken: ${NPM_TOKEN}" >> .yarnrc.yml
    else
      echo "NPM_TOKEN not defined, skip npm login"
    fi

# Ensure we can build a package in MR
test-build-npm-leav-types:
  stage: test
  script:
    - yarn workspaces focus core
    - yarn workspace @aristid/leav-types generate
  cache:
    <<: *yarn_cache
  rules:
    - *disable_publish_npm_rule
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        # libs/types is a projection of apps/core
        - apps/core/**/*
        - *new_lib_installed_changes
      when: on_success

test-build-npm-leav-ui:
  stage: test
  script:
    - yarn workspaces focus @leav/ui
    - yarn workspace @leav/ui build
  cache:
    <<: *yarn_cache
  rules:
    - *disable_publish_npm_rule
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - libs/ui/**/*
        - *new_lib_installed_changes
      when: on_success

test-build-npm-leav-utils:
  stage: test
  script:
    - yarn workspaces focus @leav/utils
    - yarn workspace @leav/utils build
  cache:
    <<: *yarn_cache
  rules:
    - *disable_publish_npm_rule
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - libs/utils/**/*
        - *new_lib_installed_changes
      when: on_success

publish-npm-leav-types-next:
  stage: build
  script:
    - apk add --no-cache jq
    - *login_npm_registry_script
    - VERSION=$(npm --silent -workspace @aristid/leav-types run get-version)-$CI_COMMIT_SHORT_SHA
    - |
      echo "Check if version @aristid/leav-types@$VERSION already exists on npm"
      EXISTS=$(npm --silent view @aristid/leav-types@$VERSION version || echo "")
      if [ -n "$EXISTS" ]; then
        echo "Version @aristid/leav-types@$VERSION already exists on npm, skipping publish."
      else
        echo "Publishing @aristid/leav-types@$VERSION to npm"
        echo yarn workspaces focus core
        yarn workspaces focus core
        echo yarn workspace @aristid/leav-types generate
        yarn workspace @aristid/leav-types generate
        # Do not use 'yarn workspace @aristid/leav-types version xxx' because it needs git !
        echo yarn workspace @aristid/leav-types set-version -- $VERSION
        yarn workspace @aristid/leav-types set-version -- $VERSION
        echo yarn workspace @aristid/leav-types publish-types --tag next
        yarn workspace @aristid/leav-types publish-types --tag next
      fi
  cache:
    <<: *yarn_cache
  rules:
    - *disable_publish_npm_rule
    - if: $CI_COMMIT_BRANCH == "develop"
      changes:
        # libs/types is a projection of apps/core
        - apps/core/**/*
      when: on_success

publish-npm-leav-types-latest:
  stage: build
  script:
    - apk add --no-cache jq
    - *login_npm_registry_script
    - VERSION=$(npm --silent -workspace @aristid/leav-types run get-version)
    - |
      echo "Check if version @aristid/leav-types@$VERSION already exists on npm"
      EXISTS=$(npm --silent view @aristid/leav-types@$VERSION version || echo "")
      if [ -n "$EXISTS" ]; then
        echo "Version @aristid/leav-types@$VERSION already exists on npm, skipping publish."
      else
        echo "Publishing @aristid/leav-types@$VERSION to npm"
        echo yarn workspaces focus core
        yarn workspaces focus core
        echo yarn workspace @aristid/leav-types generate
        yarn workspace @aristid/leav-types generate
        # Do not use 'yarn workspace @aristid/leav-types version xxx' because it needs git !
        echo yarn workspace @aristid/leav-types set-version -- $VERSION
        yarn workspace @aristid/leav-types set-version -- $VERSION
        echo yarn workspace @aristid/leav-types publish-types --tag latest
        yarn workspace @aristid/leav-types publish-types --tag latest
      fi
  cache:
    <<: *yarn_cache
  rules:
    - *disable_publish_npm_rule
    - if: $CI_COMMIT_TAG
      when: on_success

publish-npm-leav-ui-next:
  stage: build
  script:
    - apk add --no-cache jq
    - *login_npm_registry_script
    - VERSION=$(npm --silent -workspace @leav/ui run get-version)-$CI_COMMIT_SHORT_SHA
    - |
      echo "Check if version @leav/ui@$VERSION already exists on npm"
      EXISTS=$(npm --silent view @leav/ui@$VERSION version || echo "")
      if [ -n "$EXISTS" ]; then
        echo "Version @leav/ui@$VERSION already exists on npm, skipping publish."
      else
        echo "Publishing @leav/ui@$VERSION to npm"
        echo yarn workspaces focus @leav/ui
        yarn workspaces focus @leav/ui
        echo yarn workspace @leav/ui build
        yarn workspace @leav/ui build
        # Do not use 'yarn workspace @leav/ui version xxx' because it needs git !
        echo yarn workspace @leav/ui set-version -- $VERSION
        yarn workspace @leav/ui set-version -- $VERSION
        echo yarn workspace @leav/ui publish-ui --tag next
        yarn workspace @leav/ui publish-ui --tag next
      fi
  cache:
    <<: *yarn_cache
  rules:
    - *disable_publish_npm_rule
    - if: $CI_COMMIT_BRANCH == "develop"
      changes:
        - libs/ui/**/*
      when: on_success

publish-npm-leav-ui-latest:
  stage: build
  when: manual
  script:
    - apk add --no-cache jq
    - *login_npm_registry_script
    - VERSION=$(npm --silent -workspace @leav/ui run get-version)
    - |
      echo "Check if version @leav/ui@$VERSION already exists on npm"
      EXISTS=$(npm --silent view @leav/ui@$VERSION version || echo "")
      if [ -n "$EXISTS" ]; then
        echo "Version @leav/ui@$VERSION already exists on npm, skipping publish."
      else
        echo "Publishing @leav/ui@$VERSION to npm"
        echo yarn workspaces focus @leav/ui
        yarn workspaces focus @leav/ui
        echo yarn workspace @leav/ui build
        yarn workspace @leav/ui build
        echo yarn workspace @leav/ui publish-ui --tag latest
        yarn workspace @leav/ui publish-ui --tag latest
      fi
  cache:
    <<: *yarn_cache
  rules:
    - *disable_publish_npm_rule
    - if: $CI_COMMIT_TAG
      when: on_success

publish-npm-leav-utils-latest:
  stage: build
  when: manual
  script:
    - apk add --no-cache jq
    - *login_npm_registry_script
    - VERSION=$(npm --silent -workspace @leav/utils run get-version)
    - |
      echo "Check if version @leav/utils@$VERSION already exists on npm"
      EXISTS=$(npm --silent view @leav/utils@$VERSION version || echo "")
      if [ -n "$EXISTS" ]; then
        echo "Version @leav/utils@$VERSION already exists on npm, skipping publish."
      else
        echo "Publishing @leav/utils@$VERSION to npm"
        echo yarn workspaces focus @leav/utils
        yarn workspaces focus @leav/utils
        echo yarn workspace @leav/utils build
        yarn workspace @leav/utils build
        echo yarn workspace @leav/utils publish-utils --tag latest
        yarn workspace @leav/utils publish-utils --tag latest
      fi
  cache:
    <<: *yarn_cache
  rules:
    - *disable_publish_npm_rule
    - if: $CI_COMMIT_TAG
      when: on_success
## Publish npm packages
##########
