compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: node-modules

# new default value blocks aristid-ds (and other packages) installation for 1 day after publishing
npmMinimalAgeGate: 0

yarnPath: .yarn/releases/yarn-4.15.0.cjs
