query getTreeLibrariesForExplorer($treeId: [ID!]) {
    trees(filters: {id: $treeId}) {
        totalCount
        list {
            id
            behavior
            system
            libraries {
                library {
                    id
                    label
                    behavior
                    system
                }
                settings {
                    allowMultiplePositions
                    allowedChildren
                    allowedAtRoot
                }
            }
        }
    }
}
