fragment SaveValuePayload on Value {
    id_value
    payload
}

fragment SaveLinkValuePayload on LinkValue {
    id_value
    linkPayload: payload {
        id
    }
}

fragment SaveTreeValuePayload on TreeValue {
    id_value
    treePayload: payload {
        id
    }
}

mutation SaveValueBatch($library: ID, $recordId: ID, $values: [ValueBatchInput], $deleteEmpty: Boolean) {
    saveValueBatch(library: $library, recordId: $recordId, values: $values, deleteEmpty: $deleteEmpty) {
        errors {
            type
            message
            input
            attribute
        }
        values {
            id_value
            ...SaveValuePayload
            ...SaveLinkValuePayload
            ...SaveTreeValuePayload
        }
    }
}

mutation SaveValue($libraryId: ID!, $attributeId: ID!, $value: ValueInput!, $recordId: ID!) {
    saveValue(library: $libraryId, attribute: $attributeId, value: $value, recordId: $recordId) {
        id_value
        ...SaveValuePayload
        ...SaveLinkValuePayload
        ...SaveTreeValuePayload
    }
}

mutation DeleteValue($library: ID!, $recordId: ID!, $attribute: ID!, $value: ValueInput) {
    deleteValue(library: $library, recordId: $recordId, attribute: $attribute, value: $value) {
        id_value
        ...SaveValuePayload
        ...SaveLinkValuePayload
        ...SaveTreeValuePayload
    }
}

query GetRecordByIdStandardValuesProperty($libraryId: ID!, $recordId: String!, $attributeId: ID!) {
    records(library: $libraryId, filters: [{field: "id", condition: EQUAL, value: $recordId}]) {
        list {
            id
            whoAmI {
                library {
                    id
                }
            }
            active
            property(attribute: $attributeId) {
                ... on Value {
                    id_value
                    payload
                }
            }
        }
    }
}
