/* eslint-disable @typescript-eslint/naming-convention */
// should match enum generated by graphql in libs/ui/src/_gqlTypes/index.ts
export enum AttributeType {
    advanced = 'advanced',
    advanced_link = 'advanced_link',
    simple = 'simple',
    simple_link = 'simple_link',
    tree = 'tree',
}
