# TODO rename GetRecordById (and maybe more specific if test dedicated to this query)
query GetRecord($libraryId: ID!, $recordId: String!) {
    records(library: $libraryId, filters: [{field: "id", condition: EQUAL, value: $recordId}]) {
        list {
            id
            modified_at
        }
    }
}

mutation CreateRecord($library: ID!, $data: CreateRecordDataInput) {
    createRecord(library: $library, data: $data) {
        valuesErrors {
            attribute
            input
            message
            type
        }
        record {
            id
            uuid
        }
    }
}

mutation DeleteRecord($id: ID, $library: ID) {
    deleteRecord(id: $id, library: $library) {
        id
    }
}

mutation PurgeInactiveRecords($libraryId: String!) {
    purgeInactiveRecords(libraryId: $libraryId) {
        id
    }
}

query GetRecordByUUID($libraryId: ID!, $recordUUID: String!, $retrieveInactive: Boolean) {
    records(
        library: $libraryId
        filters: [{field: "uuid", condition: EQUAL, value: $recordUUID}]
        retrieveInactive: $retrieveInactive
    ) {
        list {
            id
            uuid
            active
            created_by: property(attribute: "created_by") {
                ... on LinkValue {
                    payload {
                        id
                    }
                }
            }
            modified_by: property(attribute: "modified_by") {
                ... on LinkValue {
                    payload {
                        id
                    }
                }
            }
            created_at
            modified_at
        }
    }
}
