# TODO rename GetRecordById (and maybe more specific if test dedicated to this query)
query GetRecord($libraryId: ID!, $recordId: String!) {
    records(library: $libraryId, filters: [{field: "id", condition: EQUAL, value: $recordId}]) {
        list {
            id
            modified_at
        }
    }
}

mutation CreateRecord($library: ID!, $data: CreateRecordDataInput, $skipActivate: Boolean) {
    createRecord(library: $library, data: $data, skipActivate: $skipActivate) {
        valuesErrors {
            attribute
            input
            message
            type
        }
        record {
            id
            uuid
        }
    }
}

mutation DeleteRecord($id: ID, $library: ID) {
    deleteRecord(id: $id, library: $library) {
        id
    }
}

mutation ActivateNewRecord($library: ID!, $recordId: ID!) {
    activateNewRecord(library: $library, recordId: $recordId) {
        record {
            id
        }
    }
}

mutation DeactivateRecords(
    $libraryId: String!
    $recordsIds: [String!]
    $filters: [RecordFilterInput!]
    $searchQuery: String
) {
    deactivateRecords(libraryId: $libraryId, recordsIds: $recordsIds, filters: $filters, searchQuery: $searchQuery) {
        id
    }
}

query SearchRecords($libraryId: ID!, $searchQuery: String, $filters: [RecordFilterInput], $retrieveInactive: Boolean) {
    records(library: $libraryId, searchQuery: $searchQuery, filters: $filters, retrieveInactive: $retrieveInactive) {
        totalCount
        list {
            id
            active
        }
    }
}

mutation PurgeInactiveRecords($libraryId: String!) {
    purgeInactiveRecords(libraryId: $libraryId) {
        id
    }
}

query GetRecordByUUID($libraryId: ID!, $recordUUID: String!, $retrieveInactive: Boolean) {
    records(
        library: $libraryId
        filters: [{field: "uuid", condition: EQUAL, value: $recordUUID}]
        retrieveInactive: $retrieveInactive
    ) {
        list {
            id
            uuid
            active
            created_by: property(attribute: "created_by") {
                ... on LinkValue {
                    payload {
                        id
                    }
                }
            }
            modified_by: property(attribute: "modified_by") {
                ... on LinkValue {
                    payload {
                        id
                    }
                }
            }
            whoAmI {
                label
            }
            created_at
            modified_at
        }
    }
}
