query getAutomationRulesData(
    $filters: AutomationRulesFiltersInput
    $pagination: Pagination
    $sort: AutomationRulesSortInput
) {
    automationRules(filters: $filters, pagination: $pagination, sort: $sort) {
        totalCount
        list {
            id
            label
            version
            active
            modifiedAt
            modifiedBy {
                whoAmI {
                    label
                }
            }
            trigger {
                eventAction
                eventTopic {
                    library
                    attribute
                }
            }
            pipeline {
                steps {
                    name
                }
            }
        }
    }
}
