##################################################################################################
#                                      RECEIVERS                                                 #
##################################################################################################
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

##################################################################################################
#                                      PROCESSORS                                                #
##################################################################################################
processors:
  batch:
    send_batch_size: 1000
    timeout: 5s
    send_batch_max_size: 1500
  memory_limiter:
    limit_mib: 256
    check_interval: 1s

  # Inject Kubernetes attributes into metrics and traces, to have same queries in dashboards and traces.
  attributes/inject_k8s_attributes:
    actions:
      - key: k8s_namespace_name
        value: xs-local
        action: insert
##################################################################################################
#                                      EXPORTERS                                                 #
##################################################################################################
exporters:
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
  debug:
    verbosity: basic # normal | basic | detailed

##################################################################################################
#                                      SERVICES                                                  #
##################################################################################################
service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, attributes/inject_k8s_attributes, batch]
      exporters: [prometheusremotewrite, debug]
