fragment RecordHistoryLogAttribute on LogAttribute {
    ... on StandardAttribute {
        id
        label
        type
        format
        multiple_values
        embedded_fields {
            id
            label
        }
    }
    ... on LinkAttribute {
        id
        label
        type
        format
        multiple_values
    }
    ... on TreeAttribute {
        id
        label
        type
        format
        multiple_values
    }
}

fragment RecordHistoryLogEntry on Log {
    action
    time
    topic {
        attribute {
            ...RecordHistoryLogAttribute
            ... on LogUnknownEntity {
                id
                label
            }
        }
    }
    user {
        ... on Record {
            id
            whoAmI {
                # Don't know why, but frontend need that to load record !
                id
                library {
                    id
                }
            }
            properties(attributeIds: ["email"]) {
                attributeId
                values {
                    ... on Value {
                        payload
                    }
                }
            }
        }
        ... on LogUnknownEntity {
            id
            label
        }
    }
    before {
        asString
    }
    after {
        asString
    }
}

query getRecordHistory(
    $record: LogTopicRecordFilterInput!
    $attributeId: String
    $actions: [LogAction!]
    $pagination: Pagination
) {
    logs(filters: {topic: {record: $record, attribute: $attributeId}, actions: $actions}, pagination: $pagination) {
        total
        logs {
            ...RecordHistoryLogEntry
        }
    }
}
