query GetRecordIdCard($id: String, $libraryId: ID!, $ignoreAccessRecordByDefaultPermission: Boolean!) {
    records(
        library: $libraryId
        filters: [{field: "id", condition: EQUAL, value: $id}]
        ignoreAccessRecordByDefaultPermission: $ignoreAccessRecordByDefaultPermission
    ) {
        list {
            id
            whoAmI {
                id
                color
                label
                subLabel
                preview
                parentContext {
                    id
                    label
                }
            }
        }
    }
}
