mutation CreateViewV2($view: ViewV2CreateInput!) {
    createViewV2(view: $view) {
        id
    }
}

query GetViewsV2($library: ID!, $origin: String) {
    viewsV2(library: $library, origin: $origin) {
        totalCount
        list {
            id
            created_by {
                id
                whoAmI {
                    id
                    label
                }
            }
            display {
                type
                attributes {
                    attribute {
                        id
                    }
                    visible
                }
                settings
            }
            modified_at
            created_at
            shared
            label
            origin
            filters {
                pinned
                attributes {
                    id
                }
                values
                condition
                withEmptyValues
            }
            sorts {
                activated
                attributes {
                    id
                }
                order
            }
            shortcuts
        }
    }
}

query GetViewV2($viewId: ID!) {
    viewV2(viewId: $viewId) {
        id
        created_by {
            id
            whoAmI {
                id
                label
            }
        }
    }
}

mutation UpdateViewV2($view: ViewV2UpdateInput!) {
    updateViewV2(view: $view) {
        id
        display {
            type
            settings
        }
        origin
    }
}

mutation DeleteViewV2($viewId: ID!) {
    deleteViewV2(viewId: $viewId) {
        id
    }
}
