query getAutomationRuleDetails(
    $filters: AutomationRulesFiltersInput
    $pagination: Pagination
    $sort: AutomationRulesSortInput
) {
    automationRules(filters: $filters, pagination: $pagination, sort: $sort) {
        list {
            id
            label
            description
            active
            trigger {
                eventAction
                eventTopic {
                    library
                    attribute
                }
                synchronous
            }
            pipeline {
                steps {
                    type
                    name
                    params
                }
            }
        }
    }
}
