mutation SaveApiKey($apiKey: ApiKeyInput!) {
    saveApiKey(apiKey: $apiKey) {
        id
        label
        key
        expiresAt
        user {
            id
        }
        createdBy {
            id
        }
        modifiedBy {
            id
        }
    }
}

query GetApiKeys {
    apiKeys {
        list {
            id
            label
            key
            expiresAt
            user {
                id
            }
        }
    }
}

mutation DeleteApiKey($id: String!) {
    deleteApiKey(id: $id) {
        id
    }
}
