fragment LinkAttributeDetails on LinkAttribute {
    label
    linked_library {
        id
        label
    }
    values_list {
        allowFreeEntry
        enable
        values {
            id
            whoAmI {
                id
                library {
                    id
                }
            }
        }
    }
}

fragment TreeAttributeDetails on TreeAttribute {
    id
    label
    linked_tree {
        id
        label
    }
}

query ExplorerAttributes($ids: [ID!]) {
    attributes(filters: { ids: $ids }) {
        list {
            id
            type
            format
            label
            permissions {
                access_attribute
            }
            ...LinkAttributeDetails
            ...TreeAttributeDetails
        }
    }
}

query ExplorerLinkAttribute($id: ID!) {
    attributes(filters: { ids: [$id] }) {
        list {
            id
            multiple_values
            permissions {
                access_attribute
                edit_value
            }
            ...LinkAttributeDetails
            ...TreeAttributeDetails
        }
    }
}
