query MassEditableAttributes($libraryId: String!) {
    attributes(filters: {multiple_values: false, type: tree, libraries: [$libraryId]}) {
        list {
            id
            label
            ... on TreeAttribute {
                id
                permissions_conf_dependent_values {
                    dependenciesTreeAttributes {
                        id
                        label
                        ... on TreeAttribute {
                            linked_tree {
                                libraries {
                                    library {
                                        id
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
