mutation ImportData($file: Upload!) {
    importData(file: $file)
}

query GetRecords($library: ID!) {
    records(library: $library, retrieveInactive: true) {
        list {
            id
        }
    }
}

mutation DeactivateRecords($libraryId: String!, $recordsIds: [String!]!) {
    deactivateRecords(libraryId: $libraryId, recordsIds: $recordsIds) {
        id
    }
}

mutation PurgeRecord($libraryId: ID!, $recordId: ID!) {
    purgeRecord(libraryId: $libraryId, recordId: $recordId) {
        id
    }
}
