query GetAutomationRules($filters: AutomationRulesFiltersInput) {
    automationRules(filters: $filters) {
        list {
            id
            label
            description
            version
            active
            createdAt
            createdBy
            modifiedAt
            modifiedBy {
                id
            }
            trigger {
                synchronous
                eventAction
                eventTopic {
                    library
                }
            }
            pipeline {
                steps {
                    type
                    name
                    params
                }
            }
        }
    }
}

mutation CreateAutomationRule($rule: CreateAutomationRuleInput!) {
    createAutomationRule(rule: $rule) {
        id
        label
        modifiedAt
        active
        trigger {
            synchronous
            eventAction
            eventTopic {
                library
            }
        }
        pipeline {
            steps {
                type
                name
                params
            }
        }
    }
}

mutation UpdateAutomationRule($rule: UpdateAutomationRuleInput!) {
    updateAutomationRule(rule: $rule) {
        id
        label
        description
        active
        modifiedAt
        trigger {
            synchronous
            eventAction
            eventTopic {
                library
            }
        }
        pipeline {
            steps {
                type
                name
                params
            }
        }
    }
}

mutation DuplicateAutomationRule($ruleId: ID!, $label: String!) {
    duplicateAutomationRule(ruleId: $ruleId, label: $label) {
        id
        label
        description
        version
        active
        trigger {
            synchronous
            eventAction
            eventTopic {
                library
            }
        }
        pipeline {
            steps {
                type
                name
                params
            }
        }
    }
}

mutation DeleteAutomationRule($ruleId: ID!) {
    deleteAutomationRule(ruleId: $ruleId) {
        id
    }
}

mutation SetAutomationRulesActive($ruleIds: [ID!]!, $active: Boolean!) {
    setAutomationRulesActive(ruleIds: $ruleIds, active: $active) {
        id
        active
    }
}

mutation DeleteAutomationRules($ruleIds: [ID!]!) {
    deleteAutomationRules(ruleIds: $ruleIds) {
        id
    }
}

query GetAutomationRuleForm($formType: AutomationRuleJsonSchemaFormType!) {
    automationRuleForm(formType: $formType) {
        jsonSchema
        uiSchema
    }
}
