query GetAutomationRules($filters: AutomationRulesFiltersInput) {
    automationRules(filters: $filters) {
        list {
            id
            label
            description
            active
            createdAt
            createdBy
            modifiedAt
            modifiedBy
            trigger {
                synchronous
                eventAction
                eventTopic {
                    library
                }
            }
        }
    }
}

mutation CreateAutomationRule($rule: CreateAutomationRuleInput!) {
    createAutomationRule(rule: $rule) {
        id
        label
        modifiedAt
        trigger {
            synchronous
            eventAction
            eventTopic {
                library
            }
        }
    }
}

mutation UpdateAutomationRule($rule: UpdateAutomationRuleInput!) {
    updateAutomationRule(rule: $rule) {
        id
        label
        description
        active
        modifiedAt
        trigger {
            synchronous
            eventAction
            eventTopic {
                library
            }
        }
    }
}

mutation DeleteAutomationRule($ruleId: ID!) {
    deleteAutomationRule(ruleId: $ruleId) {
        id
    }
}

query ListAutomationTriggersDef {
    automationTriggersDef {
        eventAction
        topics
        synchronicity
    }
}
