query GetUsers($query: String!, $pagination: RecordsPagination) {
    records(
        library: "users"
        filters: [
            {field: "login", condition: NOT_EQUAL, value: ""}
            {operator: AND}
            {field: "email", condition: NOT_EQUAL, value: ""}
            {operator: AND}
            {field: "login", condition: CONTAINS, value: $query}
        ]
        pagination: $pagination
    ) {
        list {
            id
            label: property(attribute: "login") {
                ... on Value {
                    payload
                }
            }
        }
    }
}
