#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

export NVM_DIR="$HOME/.nvm/nvm.sh"
. "$(dirname $NVM_DIR)/nvm.sh"

export NVM_DIR="$HOME/.nvm"
a=$(nvm ls | grep 'node')
b=${a#*(-> }
v=${b%%[)| ]*}

export PATH="$NVM_DIR/versions/node/$v/bin:$PATH"

export SKIP_PREFLIGHT_CHECK=true
export CI=true

echo "Checking types..."
yarn run tscheck

echo "\n Checking staged files..."
yarn lint-staged

echo "\n Running tests..."
yarn run test --staged