#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

export SKIP_PREFLIGHT_CHECK=true

echo "Checking types..."
yarn run tscheck

echo "\n Checking staged files..."
yarn lint-staged

echo "\n Running tests..."
yarn run test