export {default as actionList} from './actionListApp';
export {default as attribute} from './attributeApp/attributeApp';
export {default} from './coreApp';
export {default as filesManager} from './filesManagerApp';
export {default as library} from './libraryApp';
export {default as permission} from './permissionApp';
export {default as plugins} from './pluginsApp';
export {default as record} from './recordApp';
export {default as tree} from './treeApp';
export {default as value} from './valueApp';
