name: "Publish @leav/types @next package to npmjs on push on develop"

on:
  push:
    branches:
      - feature/export-plugin-types-in-leav-ui
    paths:
      - libs/types/**
  # workflow_dispatch:
  #   secrets:
  #     NPM_TOKEN:
  #       description: 'Npm Token
jobs:
  install:
    uses: ./.github/workflows/install.yml
  copy-types:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'develop'
      - name: Copy types
        run: yarn workspace core tsc --emitDeclarationOnly --declaration && cp -r ./apps/core/dist/* ./libs/types
  prepublish:
    runs-on: ubuntu-latest
    needs: copy-types
    outputs:
      version: ${{ steps.version.outputs.next_version }}
      exists: ${{ steps.check.outputs.exists }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'develop'
      - name: get next version
        id: version
        run: |
          echo "next_version=$(cat libs/types/package.json | jq -r '.version')-$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_OUTPUT"
          echo "next_version=$(cat libs/types/package.json | jq -r '.version')-$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Update package.json version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: libs/types/package.json
          field: version
          value: ${{ env.next_version }}
      - name: Check publish status
        id: check_npm
        uses: tehpsalmist/npm-publish-status-action@v1
      - name: set check npm variable
        id: check
        run: |
          echo "exists=${{ steps.check_npm.outputs.exists }}" >> "$GITHUB_OUTPUT"
