name: "Publish @leav/ui @latest package to npmjs on push on develop"

on:
  workflow_dispatch:
    secrets:
      NPM_TOKEN:
        description: 'Npm Token'
        required: true

jobs:
  install:
    uses: ./.github/workflows/install.yml
  publish-latest:
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'develop'
          fetch-depth: 0
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
      - name: Update package.json version
        run: yarn workspace @leav/ui version minor
      - name: Commit and push changes
        run: "git add libs/ui/package.json && git commit -m 'chore(@leav/ui): update to next minor version' && git push"
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: build project
        run: yarn workspace @leav/ui build
      - name: publish latest version
        run: yarn workspace @leav/ui publish-ui --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

